version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:2.5.9-node
    steps:
      - setup_remote_docker

      - run:
          name: Ruby version
          command: ruby -v

      - run:
          name: Install Sqlite3 libs
          command: |
              sudo apt-get update
              sudo apt-get install libsqlite3-dev

      - run:
          name: Install Docker Machine
          command: |
              base=https://github.com/docker/machine/releases/download/v0.16.0 &&
                curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
                sudo install /tmp/docker-machine /usr/local/bin/docker-machine

      - checkout

      - run:
          name: Build image
          command: $(pwd)/build.sh

      - run:
          name: Run tests
          command: $(pwd)/test.sh

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            fi
